#!/usr/bin/env node
/**
 * forgewright — Global MCP Server
 * Works with ANY project - workspace determined by FORGEWRIGHT_WORKSPACE env var
 * 
 * Auto-generated by Forgewright Global Setup
 */

import { startMCPServer } from "gitnexus/dist/mcp/server.js";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

// ─── Configuration ──────────────────────────────────────────────
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Workspace: Priority 1 = FORGEWRIGHT_WORKSPACE env var
//            Priority 2 = computed from __dirname
const FORGEWRIGHT_WORKSPACE = process.env.FORGEWRIGHT_WORKSPACE;
const FORGEWRIGHT_DIR = process.env.FORGEWRIGHT_DIR || resolve(__dirname, "../..");

// Determine project root
let PROJECT_ROOT;
if (FORGEWRIGHT_WORKSPACE) {
    PROJECT_ROOT = FORGEWRIGHT_WORKSPACE;
} else {
    // Compute from __dirname: go up to project root
    // Path: .forgewright/mcp-server/ -> .forgewright/ -> project root
    PROJECT_ROOT = resolve(__dirname, "../..");
}

process.title = "forgewright-mcp";

console.error(`[ForgeWright MCP] Starting with workspace: ${PROJECT_ROOT}`);
console.error(`[ForgeWright MCP] Forgewright dir: ${FORGEWRIGHT_DIR}`);

// ─── Start Native Server ────────────────────────────────────────

startMCPServer(PROJECT_ROOT).catch((err: any) => {
    console.error(`[ForgeWright MCP] Fatal error: ${err.message}`);
    console.error(err.stack);
    process.exit(1);
});
