#!/usr/bin/env python3
"""
scripts/lite/sync-kernel.py
Dynamically generates CLAUDE.md, AGENTS.md, and GEMINI.md from kernel files
to eliminate duplication, drift, and ensure boot context remains under 7k tokens.
"""

import os
import sys

# Find project root
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
KERNEL_DIR = os.path.join(PROJECT_ROOT, "kernel")
LITE_FILES = ["ENTRY.md", "SOLVE.md", "VERIFY.md", "ESCALATE.md", "CLARIFY.md"]

TARGETS = {
    "CLAUDE.md": {
        "title": "# Forgewright Kernel LITE — Claude Code",
        "description": "This file is read by Claude Code on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "AGENTS.md": {
        "title": "# Forgewright Kernel LITE — Antigravity / Cursor",
        "description": "This file is read by Antigravity / Cursor on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "GEMINI.md": {
        "title": "# Forgewright Kernel LITE — Gemini",
        "description": "This file is read by Gemini on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
}


def estimate_tokens(text):
    # Deterministic token estimation
    return len(text) // 4


def sync():
    print(f"Reading kernel files from: {KERNEL_DIR}")
    kernel_contents = []

    for filename in LITE_FILES:
        filepath = os.path.join(KERNEL_DIR, filename)
        if not os.path.exists(filepath):
            print(f"Error: Required kernel file '{filepath}' does not exist.")
            sys.exit(1)

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()
            # Clean up links to kernel files so agents don't try to reread them
            import re

            content = re.sub(
                r"\[kernel/([A-Z]+)\.md\]\([^)]+\)", r"\1 section", content
            )
            kernel_contents.append(
                f"<!-- START OF {filename} -->\n{content}\n<!-- END OF {filename} -->"
            )

    combined_kernel = "\n\n".join(kernel_contents)
    total_kernel_tokens = estimate_tokens(combined_kernel)
    print(f"Kernel source files estimate: {total_kernel_tokens} tokens")

    has_error = False
    for target_name, info in TARGETS.items():
        target_path = os.path.join(PROJECT_ROOT, target_name)

        # Preserve post-kernel sections (e.g., GitNexus) from existing file
        preserved_sections = ""
        if os.path.exists(target_path):
            with open(target_path, "r", encoding="utf-8") as f:
                existing = f.read()
            import re

            # Find all <!-- marker:start --> ... <!-- marker:end --> blocks
            for marker in ["gitnexus", "forgenexus"]:
                pattern = rf"(<!-- {marker}:start -->.*?<!-- {marker}:end -->)"
                match = re.search(pattern, existing, re.DOTALL)
                if match:
                    preserved_sections += "\n" + match.group(1) + "\n"

        content = f"""{info["title"]}

> **DO NOT EDIT THIS FILE DIRECTLY.** It is dynamically generated by the sync script.
> Source of truth resides in the `kernel/` directory. Run `python3 scripts/lite/sync-kernel.py` to regenerate.

{info["description"]}

---

{combined_kernel}
{preserved_sections}"""

        with open(target_path, "w", encoding="utf-8") as f:
            f.write(content)

        target_tokens = estimate_tokens(content)
        status = "OK" if target_tokens < 7000 else "EXCEEDED LIMIT"
        preserved_note = (
            " (preserved post-kernel sections)" if preserved_sections else ""
        )
        print(
            f"Generated: {target_name} ({target_tokens} est. tokens) -> [{status}]{preserved_note}"
        )

        if target_tokens >= 7000:
            print(
                f"Error: {target_name} exceeds the 7k deterministic token budget limit!",
                file=sys.stderr,
            )
            has_error = True

    if has_error:
        sys.exit(1)


if __name__ == "__main__":
    sync()
