#!/usr/bin/env python3
"""
scripts/lite/sync-kernel.py
Dynamically generates CLAUDE.md, AGENTS.md, and GEMINI.md from kernel files
to eliminate duplication, drift, and ensure boot context remains under 7k tokens.
"""

import os
import sys

# Find project root
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
KERNEL_DIR = os.path.join(PROJECT_ROOT, "kernel")
LITE_FILES = ["ENTRY.md", "SOLVE.md", "VERIFY.md", "ESCALATE.md", "CLARIFY.md"]

TARGETS = {
    "CLAUDE.md": {
        "title": "# Forgewright Kernel LITE — Claude Code",
        "description": "This file is read by Claude Code on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "AGENTS.md": {
        "title": "# Forgewright Kernel LITE — Antigravity / Cursor",
        "description": "This file is read by Antigravity / Cursor on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "GEMINI.md": {
        "title": "# Forgewright Kernel LITE — Gemini",
        "description": "This file is read by Gemini on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
}


def estimate_tokens(text):
    # Standard approximation: 1 token ~ 4 characters
    char_count = len(text)
    word_count = len(text.split())
    # Take the average of char-based and word-based estimation
    # 1 token ~ 0.75 words, so words / 0.75 = words * 1.33
    token_est = int((char_count / 4.0 + word_count * 1.33) / 2.0)
    return token_est


def sync():
    print(f"Reading kernel files from: {KERNEL_DIR}")
    kernel_contents = []

    for filename in LITE_FILES:
        filepath = os.path.join(KERNEL_DIR, filename)
        if not os.path.exists(filepath):
            print(f"Error: Required kernel file '{filepath}' does not exist.")
            sys.exit(1)

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()
            # Clean up relative file links so they work from the project root
            # Convert file:///Users/buiphucminhtam/GitHub/forgewright/kernel/X.md to file://./kernel/X.md or keep absolute
            # Let's keep them absolute as generated or simplify them.
            kernel_contents.append(
                f"<!-- START OF {filename} -->\n{content}\n<!-- END OF {filename} -->"
            )

    combined_kernel = "\n\n".join(kernel_contents)
    total_kernel_tokens = estimate_tokens(combined_kernel)
    print(f"Kernel source files estimate: {total_kernel_tokens} tokens")

    for target_name, info in TARGETS.items():
        target_path = os.path.join(PROJECT_ROOT, target_name)

        content = f"""{info["title"]}

> **DO NOT EDIT THIS FILE DIRECTLY.** It is dynamically generated by the sync script.
> Source of truth resides in the `kernel/` directory. Run `python3 scripts/lite/sync-kernel.py` to regenerate.

{info["description"]}

---

{combined_kernel}
"""

        with open(target_path, "w", encoding="utf-8") as f:
            f.write(content)

        target_tokens = estimate_tokens(content)
        status = "OK" if target_tokens < 7000 else "EXCEEDED LIMIT"
        print(f"Generated: {target_name} ({target_tokens} est. tokens) -> [{status}]")

        if target_tokens >= 7000:
            print(
                f"Warning: {target_name} is near or above the 7k token budget limit!",
                file=sys.stderr,
            )


if __name__ == "__main__":
    sync()
